### ISSUE TITLE
A question related with computing causal effect

### ISSUE THREAD

**Issue by chaojieji** [siplab-gt/generative-causal-explanations#2]
Thanks very much for your huge contribution to the field of causal explainers. I have a question after I read your outstanding paper. In Appendix D, you use a Monte-Carlo estimator to sample data from the standard normal distribution rather than the normal distributions that are learned from VAE encoder module. Is it possible for you to tell me why? I have spent a lot of time on it. However, I didn't figure out the reason. Your answer would be extremely helpful for me.

**Comment by matthewoshaughnessy** [comment]
Hi Georgie, the key idea here is that we want to estimate I(alpha; Y) rather than something involving p(encoder(X)).

An intuitive way of looking at this: our goal is to learn a VAE decoder such that a change in alpha will correspond to a large change in Y, and we do this by adding an I(alpha; Y) term to the VAE objective. When we construct a "global" explanation (i.e., one that explains the classifier in general, not one that explains how the classifier works on a certain dataset or data sample), we look at how Y changes as we perturb individual elements of alpha in a way that's not related to the encoded data distribution p(encoder(X)). When training our VAE we thus don't want to include information about p(X).

Another intuitive perspective: the causal interpretation of the explanations is based on the DAG described in Section 3.1, in which all elements of alpha and beta are independent from each other. By sampling alpha ~ N(0,I) when estimating I(alpha; Y) we ensure that correlations between elements of alpha are broken.

If you have other questions, you're welcome to send me an email: moshaughnessy6 /at gatech.edu

All the best, Matt

**Comment by chaojieji** [comment]
Thanks for your rapid response and this detailed answer. Your answer literately inspires me and clears my confusion.
